language: c

env:
  global:
    - RACKET_DIR: '~/racket'
  matrix:
    - RACKET_VERSION=6.2
    - RACKET_VERSION=6.2.1
    - RACKET_VERSION=6.3
    - RACKET_VERSION=6.4
    - RACKET_VERSION=6.5
    - RACKET_VERSION=6.6
    - RACKET_VERSION=6.7
    - RACKET_VERSION=6.8
    - RACKET_VERSION=HEAD

before_install:
  - git clone https://github.com/greghendershott/travis-racket.git
  - cat travis-racket/install-racket.sh | bash
  - export PATH="${RACKET_DIR}/bin:${PATH}"

install:
  - raco pkg install -i --auto --link
      $TRAVIS_BUILD_DIR/static-rename
      $TRAVIS_BUILD_DIR/static-rename-doc
      $TRAVIS_BUILD_DIR/static-rename-lib
      $TRAVIS_BUILD_DIR/static-rename-test

script:
  - raco test -ep static-rename-lib static-rename-test
