language: c

sudo: false

env:
  global:
    - RACKET_DIR: '~/racket'
  matrix:
    - RACKET_VERSION: 6.2
    - RACKET_VERSION: 6.2.1
    - RACKET_VERSION: 6.3
    - RACKET_VERSION: HEAD

before_install:
  - git clone https://github.com/greghendershott/travis-racket.git
  - cat travis-racket/install-racket.sh | bash
  - export PATH="${RACKET_DIR}/bin:${PATH}"

install:
  - raco pkg install -in static-rename --auto --link $TRAVIS_BUILD_DIR

script:
  - raco test -p static-rename
